# Generated by Django 3.2.4 on 2021-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='contato/%Y/%m/'),
        ),
    ]
